### ISSUE TITLE
Empty 'genindex' is generated

### ISSUE THREAD

**Issue by pooja2299** [intermine/intermine-user-docs#3] opened 2020-03-23 18:00 UTC
When clicked on 'index' option on https://flymine.readthedocs.io/en/latest/ website, an empty page containing only the template is generated (i.e. https://flymine.readthedocs.io/en/latest/genindex.html).
This might be due to broken link of index.html becuase genindex.html is not generated properly.

**Comment by fequerver** [comment] 2020-04-20 17:55
I can confirm it.

Index aren't generated because the user documentation isn't using index markups.

For a example of how to add indexes, someone can check intermine/im-docs.
Eg: Last line on https://raw.githubusercontent.com/intermine/im-docs/7dc03b68ee856c1fda76bfb8d06c31903668ec47/docs/about/index.rst

I don't know if using txt file extensions instead of rst may also have influence, I don't think so.

**Comment by uosl** [comment] 2021-04-09 09:51
Thanks for reporting this! The documentation has been completely redone since this issue was created, so I'm closing this issue.

**Closed by uosl** 2021-04-09 09:51 UTC
